type: TartanAir_NoIMU
name: abf001
args:
  # root: /home/arc/works/Detaset/UnderWater/TURTL/Data
  # Controls optional data sources
  root: /home/arc/works/Detaset/UnderWater/FLSea_Sterro_canyon1
  gtDepth: false
  gtFlow: false
  gtPose: false

  compressed: true
